- name: Initialize Kubernetes cluster
  become: yes
  shell: |
    kubeadm init \
      --pod-network-cidr={{ pod_network_cidr }} \
      --apiserver-advertise-address={{ ansible_default_ipv4.address }} \
      --node-name={{ ansible_hostname }} \
      --apiserver-cert-extra-sans={{ hostvars[inventory_hostname]['ansible_host'] }}
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  become: yes
  file:
    path: /home/{{ kube_user }}/.kube
    state: directory
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    mode: '0755'

- name: Copy admin.conf to user's kube config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ kube_user }}/.kube/config
    remote_src: yes
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    mode: '0600'

- name: Update API Server address to external IP in kubeconfig
  replace:
    path: /home/{{ kube_user }}/.kube/config
    regexp: 'https://{{ ansible_default_ipv4.address }}:6443'
    replace: 'https://{{ hostvars[inventory_hostname]["ansible_host"] }}:6443'
  become: yes

- name: Install Calico
  become: yes
  become_user: "{{ kube_user }}"
  shell: |
    kubectl apply -f {{ calico_url }}
  environment:
    KUBECONFIG: /home/{{ kube_user }}/.kube/config

- name: Generate join command
  become: yes
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Save join command
  become: yes
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/join-command.sh
    mode: '0755'

- name: Fetch join command
  fetch:
    src: /tmp/join-command.sh
    dest: /tmp/join-command.sh
    flat: yes